### ISSUE TITLE
_XEMBED_INFO not set

### ISSUE THREAD

**Issue by bernhard-da** [HarveyHunt/i3situation#14]
First of, thanks for i3situation which I've been running for quite some time now!

Today, after upgrading i3wm to 3.9 and some other arch-packages, i3situation does not draw correctly in the sense that it "overlays" itself.

Starting it from the cli I get errors
```
ERROR: Window 00e00069 violates the XEMBED protocol, _XEMBED_INFO not set
```
coming from 
```
i3bar/src/xcb.c [625]
```
I guess it has to do something with i3situation because when I use i3status, the bar is drawn as expected.

**Comment by HarveyHunt** [comment]
Thanks for your kind words - I'm sorry that not much has changed with it recently, I have been using a different window manager instead.

I'm quite busy tonight, but I'll fix this tomorrow and will update the packages.

**Comment by HarveyHunt** [comment]
I tried this out on my laptop (Arch linux + i3wm 3.9) and I couldn't reproduce this.

Can you send me some screenshots of the error and more system details please?

**Comment by bernhard-da** [comment]
hey, thx for replying . it's really strange. this is also on a fully upgraded arch (no testing) with the latest i3wm. while i was experiencing the problem with i3situation, i was switching to i3blocks porting my configuration from i3situation.

below you see the problem.

- http://s7.postimg.org/xkb1l4ofv/screenshot_i3situation.png is the result using i3situation

- http://s7.postimg.org/ex7j4yoqj/screenshot_i3blocks.png is the result using i3blocks

it seems as if the violation error is not the problem. both configurations using the same scripts so i am sure that these are not the problem either, especially because i3situation was working very well before.

**Comment by HarveyHunt** [comment]
Sorry I haven't been active recently, I've been rather busy.

Is this still happening?

**Comment by bernhard-da** [comment]
hi. no worries. actually i do not know because in the meantime i switched to i3blocks. but if you can't reproduce it it was probably just some oddity with my system....
