### ISSUE TITLE
Sugesstion: mentioning what valid .conkyrc should have

### ISSUE THREAD

**Issue by jpalczewski** [HarveyHunt/i3situation#18]
It might be nice for future users(and would help them to save a bit of time) to specify what "valid conkyrc" file means, i.e. by adding
```
conky.config = { 
...
 out_to_console = true,
 out_to_x = false,
...
}
```
to .conkyrc/conky.conf file.

**Comment by HarveyHunt** [comment]
I've added this in 3160a21006fcc6961f240988874e228a5ec6f18e - thanks.
